# Generated by Django 5.2.7 on 2025-10-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openstackuser",
            options={},
        ),
        migrations.AddField(
            model_name="openstackuser",
            name="openstack_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="openstackuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("project_manager", "Project Manager"),
                    ("member", "User"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="openstackuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "admin")),
                fields=("role",),
                name="unique_administrator_constraint",
            ),
        ),
    ]
