name: Run Black formatter
on: [push, pull_request]
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Run black
              uses: rickstaa/action-black@v1.3.3
              with:
                black_args: ". --check"
